"""
Generate CameraMatrixFallback's table from rawspeed's cameras.xml.

The bundled LibRaw (0.21.x) knows 1181 cameras and its list stops before several current bodies —
the OM System OM-5 among them. For those it parses the raw file fine but returns an identity
colour matrix, leaving the pipeline uncharacterised. rawspeed (shipped with darktable) carries
~1094 camera matrices, including newer bodies, and publishes them as the same Adobe ColorMatrix
LibRaw would have used, stored as integers scaled by 10000.

Usage:
    python3 gen_fallback_table.py [path/to/cameras.xml] > entries.txt

Default path is darktable's system copy. Paste the output into the ColorMatrix2 initialiser in
src/OpenRevelare.Core/CameraMatrixFallback.cs.

THE KEY IS THE HARD PART. The lookup happens against LibRaw's OWN make/model strings, which are
not always what rawspeed writes:

  file says     "OM Digital Solutions" / "OM-5"
  rawspeed says make="OM Digital Solutions" model="OM-5", <ID make="OM System" model="OM-5">
  LibRaw says   Make="OM Digital"        Model="OM-5"      <- this is what must match

So every plausible spelling is emitted as its own key pointing at the same matrix. Duplicate keys
cost nothing (a dictionary entry) and a missing one costs a silently uncharacterised camera.

Verification: the derivation these values feed was checked against a body LibRaw DOES know — the
E-M5 Mark III entry from this same file, pushed through CameraMatrixFallback.CameraToSrgb,
reproduces LibRaw's own rgb_cam to 1.03e-4 (float32 storage precision).
"""
import re
import sys

DEFAULT_XML = "/usr/share/darktable/rawspeed/cameras.xml"

# Makes LibRaw normalises differently from rawspeed. Left = as rawspeed writes it,
# right = extra spellings to also emit, because LibRaw may report any of them.
MAKE_ALIASES = {
    "OM Digital Solutions": ["OM Digital", "OM System", "Olympus"],
    "OLYMPUS IMAGING CORP.": ["Olympus", "OLYMPUS"],
    "OLYMPUS CORPORATION": ["Olympus", "OLYMPUS"],
    "OLYMPUS OPTICAL CO.,LTD": ["Olympus", "OLYMPUS"],
    "NIKON CORPORATION": ["Nikon", "NIKON"],
    "NIKON": ["Nikon"],
    "Canon": ["Canon"],
    "SONY": ["Sony"],
    "FUJIFILM": ["Fujifilm"],
    "Panasonic": ["Panasonic"],
    "PENTAX Corporation": ["Pentax", "PENTAX"],
    "RICOH IMAGING COMPANY, LTD.": ["Ricoh", "RICOH", "Pentax"],
    "EASTMAN KODAK COMPANY": ["Kodak", "KODAK"],
    "Leica Camera AG": ["Leica", "LEICA"],
}


def parse(xml_text):
    """Yields (make, model, id_make, id_model, [9 floats])."""
    for block in re.findall(r"<Camera[^>]*>.*?</Camera>", xml_text, re.S):
        rows = re.findall(r'<ColorMatrixRow plane="\d">([^<]+)</ColorMatrixRow>', block)
        if len(rows) != 3:
            continue
        make = re.search(r'make="([^"]*)"', block)
        model = re.search(r'model="([^"]*)"', block)
        if not (make and model):
            continue
        idtag = re.search(r"<ID[^>]*make=\"([^\"]*)\"[^>]*model=\"([^\"]*)\"", block)
        vals = []
        for r in rows:
            parts = r.split()
            if len(parts) != 3:
                break
            vals.extend(int(x) / 10000.0 for x in parts)
        if len(vals) != 9:
            continue
        yield (make.group(1), model.group(1),
               idtag.group(1) if idtag else "", idtag.group(2) if idtag else "",
               vals)


def keys_for(make, model, id_make, id_model):
    """Every plausible 'MAKE MODEL' spelling LibRaw might report for this body."""
    makes = {make}
    if id_make:
        makes.add(id_make)
    makes.update(MAKE_ALIASES.get(make, []))
    models = {model}
    if id_model:
        models.add(id_model)
    return {f"{mk} {md}".strip() for mk in makes for md in models}


def main(path):
    text = open(path, encoding="utf-8", errors="replace").read()
    # Case-INSENSITIVE dedup, because the C# dictionary is built with
    # StringComparer.OrdinalIgnoreCase: emitting both "FUJIFILM FinePix F550EXR" and
    # "Fujifilm FinePix F550EXR" would silently collapse to one entry there, so the extra
    # spelling is pure noise. (They always carry the same matrix, so nothing is lost.)
    seen = {}
    order = []
    for make, model, id_make, id_model, vals in parse(text):
        for k in sorted(keys_for(make, model, id_make, id_model)):
            fold = k.casefold()
            if fold in seen:
                continue            # first entry wins; the file lists newest last
            seen[fold] = vals
            order.append((k, make, model, vals))

    print(f"            // Generated by docs/calibration/gen_fallback_table.py from")
    print(f"            // {path} — {len(order)} keys covering rawspeed's camera matrices.")
    print(f"            // Values are Adobe ColorMatrix (XYZ D65 -> camera native), /10000.")
    print(f"            // Several keys may share a matrix: LibRaw's make/model spelling differs")
    print(f"            // from rawspeed's, so every plausible variant is listed.")
    for k, make, model, v in order:
        print(f'            ["{k}"] = new[,] {{ {{ {v[0]:.4f}, {v[1]:.4f}, {v[2]:.4f} }}, '
              f"{{ {v[3]:.4f}, {v[4]:.4f}, {v[5]:.4f} }}, "
              f"{{ {v[6]:.4f}, {v[7]:.4f}, {v[8]:.4f} }} }},")
    print(f"            // {len(order)} entries", file=sys.stderr)


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else DEFAULT_XML)
